<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Jon White: The Drinking Game</title>
    <link rel="stylesheet" href="css/main.css">
</head>
<body>
<table border="5" cellpadding="10" cellspacing="10" width="892" align="center">
	<tbody>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<img src="img/new.gif" width="64px" height="32px" alt=""> <img src="img/divider-smilies.gif" width="608px" height="25px" alt=""> <img src="img/new.gif" width="64px" height="32px" alt="">
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<h1>,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,.<span class="red">NNDDN</span>,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,<span class="red">DDDDN~</span>,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.ZMDNDDO..</span>,,,,,,,<span class="red">IDDDD8</span>,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">8DDDDDDN=</span>&nbsp;,,,,,,,<span class="red">NDDDN</span>,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<span class="red">+8NNNDDDDNZ..</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">=NDDDDDND8</span>,,,,,,,<span class="red">DDDDD8</span>,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,<span class="red">+NDDNDDDDDDDDDDN.</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.NDDDDDDDDN</span>,,,,,,<span class="red">?DDDDN</span>,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,<span class="red">=DDDDDDDDNDDNDDDDDDN</span>.&nbsp;&nbsp;&nbsp;<span class="red">+DDDD8NDNDDD</span>.,,,,<span class="red">DDDDD:</span>,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,<span class="red">+I8NN</span>,,,,,,,<span class="red">ZNDDDDN?</span>,,,,,&nbsp;<span class="red">=DNDDDDD.</span>&nbsp;&nbsp;&nbsp;<span class="red">DDDDN</span>&nbsp;<span class="red">+DDDDN=</span>,,,<span class="red">ONDDDO</span>,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
&nbsp;,,,,,,,,,,<span class="red">DDDDD?</span>,,,,,<span class="red">?DDDDDO</span>,,,,,,,.&nbsp;&nbsp;<span class="red">+NDDDNN</span>&nbsp;&nbsp;&nbsp;<span class="red">DDDDD:</span>..<span class="red">NDDDDN</span>,,<span class="red">~NDDDN</span>,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.<br>
&nbsp;&nbsp;&nbsp;,,,,,,,,<span class="red">DDDDDD</span>,,,,,<span class="red">NDDDDM</span>,,,,,,,,,&nbsp;&nbsp;<span class="red">.?DDDDD?</span>&nbsp;&nbsp;<span class="red">+DDDDD.</span>&nbsp;<span class="red">.?DDDDN$</span>,<span class="red">DDDDN=</span>,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..<br>
&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,<span class="red">=NDDDN~</span>,,,,<span class="red">DDDDDI</span>,,,,,,,,,.&nbsp;&nbsp;&nbsp;<span class="red">ODDDDN</span>&nbsp;&nbsp;<span class="red">.DDDDD,</span>&nbsp;&nbsp;&nbsp;<span class="red">.DDDDDD+DDDDN</span>,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,<span class="red">NDDDDD</span>,,,<span class="red">:NDDDN?</span>,,,,,,,,,,&nbsp;&nbsp;&nbsp;<span class="red">.DDDDD.</span>&nbsp;&nbsp;<span class="red">DDDDDN.</span>&nbsp;&nbsp;&nbsp;:<span class="red">:NDDDDDDDDN</span>,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,<span class="red">ZNDDDN:</span>,,,<span class="red">DDDDDZ</span>,,,,,,,,,,.&nbsp;&nbsp;&nbsp;<span class="red">NDDDD~</span>&nbsp;&nbsp;<span class="red">,DDDDD.</span>&nbsp;&nbsp;&nbsp;.,,<span class="red">$NDDDDDDD$</span>,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,.<span class="red">NDDDDI</span>,,,<span class="red">NDDDDN</span>,,,,,,,,,,,.&nbsp;&nbsp;<span class="red">NDDDD~</span>&nbsp;&nbsp;<span class="red">.NDDDD:</span>&nbsp;&nbsp;&nbsp;&nbsp;,,,<span class="red">:DDDDDDDN</span>,,,,,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,<span class="red">NDDDDD</span>,,,<span class="red">$DDDND:</span>,,,,,,,,,,&nbsp;&nbsp;&nbsp;<span class="red">DDDDN,</span>&nbsp;&nbsp;&nbsp;<span class="red">ZNDDD8</span>&nbsp;&nbsp;&nbsp;&nbsp;,,,,<span class="red">:$DDDDDN+</span>,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.<span class="red">~NDDDD.</span>,,,<span class="red">NDDDDN</span>,,,,,,,,,,,&nbsp;<span class="red">DDDDDN</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">,NDDDD.</span>&nbsp;&nbsp;&nbsp;.,,,,,,<span class="red">Z~</span>,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">NDDDDO</span>,,,<span class="red">:NDDDDN+</span>,,,,,,,,<span class="red">:DDDDDN,</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">8DDNN=</span>&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,::,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">ODDDDN</span>,,,,,<span class="red">DDDDDDNN+</span>~~<span class="red">?NNDDDDDD,</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">:8I</span>,..&nbsp;&nbsp;&nbsp;&nbsp;.,::~?IZ$$7I=~==~,....&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;<span class="red">.I8DNN</span>.&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.DDDDD+</span>,,,,,<span class="red">DNDDDDDDDDDDDDDDD$</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~:~~=+??I$O8DDNDND8N8N8DNDDO77?=:,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;<span class="red">.NDDDD=.</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">NDDDN7</span>,,,,,,,<span class="red">ZNNDDDDDDDDND?.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.&nbsp;.?ZOODDDDDNNNDNDDDDNDODNNOO8DDDD8OZO$7I:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">+DDDDN</span>,..&nbsp;<span class="red">=DDDDN:</span>,,,,,,,,,,,,<span class="red">++:</span>,,.,,,&nbsp;&nbsp;&nbsp;&nbsp;..:IODNMNNDNMDDDDNMMNNMMNNN8DD8DDDDDNNNDNNDOZ~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">DDDDDDDNNDDDDD$</span>&nbsp;.,,,,,,,,,,,,,,,,,,,,,&nbsp;.~$ODNMNMMNMNMDNNDNND888DDND88DD88OO8NNNM8OOZNN8Z7=:.&nbsp;,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.7DDDDDDDDDDN,</span>&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,+$8D8MMMM88MMNNO8D8888ODDZOO88DD8D88OZ8NNDND8OOZ8ZO88Z7+~:,,,,,,,,,,,,,,,,,&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">..NDDDDDN?..</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,:IZDNMMMNMN8OD8OZ8ZO8N88DNNOD8DDD8N8DNNZOOZDDDDD8D8OOODOO?Z7?~,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,:?DMMMMMMDDON88DNND888NOMNDND$DDMDNMNNMN8D877ZO8DN8DONNMDDZ$Z7I=,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,:?ONMNMMMMMD8DDDDNNNNND8N8MMDND8NNMDNMMMMM$O8ZOOOI?OOMDNMNZOD88?7I~:,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,:=ZDNMMMMMMNNNNMNNNNMMNNMDNNNNMNN87D$ODNMMMMZO8DDDND$??7$8MMO$8$DZ7Z$?~:,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,<br>
,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,:+$DNMMMMMMMMMDNNNNMMNNNDNNDMMM8MMMMNNO$IDMMMM8OOONMMMMN8$I78MMODZO8Z7DO$+:,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,<br>
,,,,,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,I8NNMMMMMMMMMNDDDMNONMMMNNMDMNMNMMMMMNNOD?$NMMMMDZODMMNDDO$$88MN8DO7I$IN8$I=&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,<br>
,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:ZDNNMMMNNMMMMMMMND8DNNDDMMDMNMMNM8NNMMNMM8Z7I7?7$8N8$NMMMNN8$$88NDNDO?$I$D8OZ+:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,<br>
,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.+8NMNNMNNMMMMMMMNNMMNNNNNNNNNNNMMMMMNMMMNMNNDM88$7~+=788DNNNOZ7OI+DD8DZ7+I~$MZD8I:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,<br>
,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,$NMMMMMNMNNNMMMNDD8DDDNNMMNNDNNMNMMMMMN8DMNMMMDN8ND$O7?O8O8DMD88$OZZ$DO8Z7+$=NDOMN7:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,<br>
,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~ZNNNMMMNMNNNMMMMMD8NNMNNNNNNNNNNNNDMMMMMMNDDMNMMN8MOO$DDO88DNMMN8D8IONDDD8Z+Z$8DODMO7.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.ZDNMMMNDDNMNDNDMDMMNNNDD8888DDDDDNNNNDDNNNNNMNNNNMNMMMNDNMNNZ78ZDNMNNDDDN88ZZOOZDD8NDO?.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$DNMNNNDDNMDNDDDNMMNNND88OOOO8OO888DDDDDDDDDD8DDDDDNNDNNDDDDDMNDND8NNDZDDDDOZOZ8DNNNN88$+..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;..8NNMNNMMMMNN8NDMMMNNDD88OOZZZ$ZZZOZZZOOOZZZZZOOZZZOOZOO888D8NDNDDD8DDD88OO$ZOOO8NNNDND8DZ~.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;~DNNNNMMMNDN8NDNNNNND8OZZZZ$$$$$$$$$$$$77777I7777777IIIIII777$$$ZZO8OZZZ$77??IZ8DNNDNDNND8I,&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,&nbsp;.ODNNMMMNDNMNNDNMMNDD8OZ$$$$7777I77777$7II7II?????????++=========+??I?=~~~::,,:+$ODDNNMMMMNZ+&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,:DNNMNNNNNNNMMMNNNND8OZ$$$$$77III77777II????++++++++++==~~:::::::::,,,,,,.,,.,,,+IODDD8DNDNZ7,.,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,ONNNNNNNNNNMMMMNNND8OZZ$$77777777777III??++++==+?+++++~~::,,,,,,,,,,,......,,,,,:+I8DDDDD88OZ?,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,:NNNNNNMMMMMMMMNNND8OZZZ$$77777777777IIII??+====+?++++=~:::,,,,,,,,,.........,...,:?$DDDDDD8OOI:,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,~DDNMMNNMMNMMNNNND8OZ$$$$$$77777777777III??+=====+++===:::,,,,,,,,,..............,,=$O888OOOOZI~:,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,~DNNMMMNNMMMMNNND8OZZ$$$$$$7777$$$$7777II???+++++==++==~:::,,,,,,.,..............,,,I7O8OO?$$OI~:,,,,,,,,,,,,,,,,,,,..<br>
&nbsp;&nbsp;&nbsp;..,,,,,,,,,,,,,,,,,~NNNNNNNNMMNMNND8OOZ$$$$$$$$$$$$7$77777III??+++++++++=~:~:,,,,,.,..,............,,,,~=$OO$$7+7I~:,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,~NNNNNNNNMNMMNDD8OZ$$$$$$$$$$77$$$$$$$7777I???++==++?+==::,,,,,,,.,.............,,..,+?I$$$$+=+:,,,,,,,,,...&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,~MNNNNNNMMNNNDDD8OZ$$$$$$$$$$$$$$$$$7$$7$77I??+++===+==~~~::~:,,,,,,,.,.......,.,,..,:=$777II++:,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.:NNNNDNNNNNNNNDDOO$$$$$$$$$$$ZZ$$$$$77II?I7I????++===~~:::::,,,,,,,,,,,,,,,,.,,,,,...:+II77I+I:&nbsp;..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MNDNNNNNNNNNNDD8O$$7$$$$$$$$$$$$$$$7777I??++++=~~~=~~~:::,:,:,,,,,...,,,,,,,,,.,,,..:=?7$7??=.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+DDNNNNNNNNNDDDOZ$$$$ZZ$$$$7$$$$7$Z$$$7II??++=~~~~:::~~~~::::,,,,,.....,,,,,,,,,,,,,,=?7$II=~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;?NDNNNNNDNNND8ZZ$$$$$ZZZZ$$$$$$$$$$ZZ$$$77II?+==~~::::::::~:::,,,,,,...,,,,,,,,,,,,,:+?77I?~,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,DDNNNNNNNDD8O$$$$$$$$$$Z$$$$$$$77$$$7I7III????+=~::::::~:~::::,,........,,,,,,,,,,,:+77II?=.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.7DDNNNNNNDDOZ$$$77$$$$$$7$777I7$$$77$77777II?++=~~::::~~~~~::,,,........,,,,,,,,,,,=I$77I+:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,O$ONNNNNNND8Z$777$$$$77III777777$77$$$$77I777??+=~,:,::~=~~~,,,,,,,,,....,,,,,,,,,,+7$7II~.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
,,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~7777ZNNNNNNDOZ$77$$$$$77II7$$$$$$$$$$$$77$7777II?=~:::~~==~~:,,,,,,,,,,.....,,,,.,,,+7$77I:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,<br>
,,,,,,,,,,,&nbsp;&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I88$$$ONNNNNDOZ$7777$7$$Z$OOZZO88DDDD88OOZ$$7777I?=~~::~==+==~,::,,,,,,,,.....,..,,,,+7$$7+&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.&nbsp;.,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;,OOOOZ$Z8NNNNDO$$$$$$7$ZOO88DNDNNMNNMMMMNNN88ZZ$77?+==~==++?+=~:,:,::::::,:,...,....,,+7$77~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,?88OZ7ZZ$ODDD8OZ$$777$$8DNNMNND8O$ZZO8DNNNMMMND8OZI?+++++=+?+===~~+?777I????I=+~:,..,,+$7+:,&nbsp;....:,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,IOOZ$$ZO$ZDND8O$7777$ZZ8NN8OOOOO8DDNMMMMMNNNNND88O$II?++===+????$Z8DNNDND88ZZ7?+~~:,,,+77:,~,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,?88Z$$Z$7$8D88Z7777777ZOO8OZONNNMMDMMM8MDNMMNNNDD8OZ7I?+~~~~+II7ZOOOOOZ$$$ZO88O$7=:,:,+7=::=,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,=ZO$$ZO8DOOD8O$Z$77777$OO88DNNND88D8DDDD7ONMNNMNDD8O$I?+:,,,=+I$$8NMMMMMMN8Z$$ZO$7?=,,+I=~,~,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,:ZZ7O88DNDZ88OZ$$7$ZZOOOOZ$$8D$$7Z$OZZ$777$DMMNNND8OO$+~,..,~=+7OZDONMNZN7OMMD7++?+?:,+=,~::,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,7$Z88DD877OOZ$$777777I77777ZO8Z$77IIIII?I7ZDNNNND8OO$?=,...:~=7$ZZZOOOZ?+7$OD8$?=~:.,+=,~~:,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,....I$Z8DDDI7$ZO$Z$$7I7777$$O$I??$ZZZ$$$$$ZZZZ8NNNDD88OO$?~,...,:=IIIII??=~~:,,:~??+,,..:+~,:,:,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.?$Z8DD8I$$ZOZ7$$Z$$7$8O77III?????+I7$$Z$ZO8DDD888OOZ7?~:,..,,:~+I$I?+==~~~:::,..,,.,:~:,,:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,&nbsp;&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+Z$ZOOZ$Z$ZOOZ$$$I$ZO77$77777I?++???III777$O8D888OZZI+~:,...,.,:::~+????=~~:,,:,..,.,~:..~.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,<br>
..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=$O7I$O$ZZ$OOZ$7I7ZZI7$7$$Z$7$I+++++??II77Z888O8ZZ$$$?+:,......,.,,:::::::,,,...,,,,,::..:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,,,,,,,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,77I$777ZZ$8OZ$7$$7I7$7$8$$777?+=+==++?I$Z8888OO$Z$$I+~:,......,,,,,,:,,,,.....,.,,,,,,...&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..&nbsp;..<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;?77Z$$OZZ$OOO$77777$7Z$77II???====++??$$88D88Z$ZZ$7I+=:.&nbsp;.....,,::::::,,......,,,,.:,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,77$ZZZZ$$OOO$7$77$Z$777IIIII+=+==+??I$O88O8ZZ$$$$7?+::.&nbsp;.....,,~~~==::,,.......,.,:..,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..7$ZZ$ZZ$O88Z$7$Z$7$77II7II?I++++???7O888OOZZZ$$$7I=:,.......,,::=+~=~::,......,,,,&nbsp;..,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.&nbsp;.I$Z$ZOO88OZ$$O7$$$7777III?+?+++?I7ODD88OOOZZ$$$7I+:,,&nbsp;&nbsp;...,,,:~~===~::,,......,,,.&nbsp;..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,::,~Z8OOZ$Z7Z$$$$$7777II?????7ZDDDD8OOZOZZ$$77?+:,,..&nbsp;...,:~===+=~~::,,.....,,,..,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,7O8O$$7ZZ$$$$7$$777II??IZDDDD88O$7$$Z$$$$7?=:,,.&nbsp;....,:=+++++=~:::,,,....,,..~,,,,,,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,?Z$$$$O$8$$$$$$777777Z8DDDD888O77$$$$$$$$7=~:,.......,~+II?+==~:,:,,,,..,,.,:,,,,,,,,,,,,.&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;,ZZ$$ZOOD$$$ZZ$7$$$$O8DDDDD8888$$$ZZZZZZZ7+==:,,.....,::?7$7?+=~::::,:,,,=:,,,,,,,,,,,,,,,,,,,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..&nbsp;&nbsp;.Z$Z$ZZ8D$ZZZ$OZ$I7O8DDDDDD88D8D8OOZOOOOOZ7I=~::,,..,,,:=+7OZI+~::,:,=:,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;.ZZZ$ZZ8D$$Z$8Z$$ZZO88DD8888DDDDDDDDDN8ZOZ$7I+::?=::,,,,::=?$8Z?~,,,,7:,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$ZZ$ZODD$77DZ$ZZOO88888888888DDDDDDDDDDO$$$7===:,,,,.,,,~~~=+Z87~,.:?:,,&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$$ZZZO8D$I7D$?ZOZOOOO8OOOO8O8O888888OZ$$ZOZ7=~:,,,,,,.,,,~~::~$DI:,:?~,:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.IZZZZO8D$IID7?IZ7ZZZZOOZZZZOOZZ$$$7I?+++++??=:::,,,,,,,,,:~~::+D7~,~=,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,ZZZZO8DZI?OO?+III$ZO8888OOOOZZZ$77I?+=~::,,,,.........,,::~::=8?:,+:,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ZOOZOOD8$?78$++????78NMMMND888OZ$777I?I++~:,,,,,,,,:::+++?+=:?I~,:~:,:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=ZOOZO8DZ$7OZ7+=???I?78MMM8D7$8888OZ$77I?+?++===++IMMMD7==~~~?~:,=:,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.+OOOOO8OZ$7O$+=+IIIIIIIZMDD+=77?77+=:?=:,,~.:,&nbsp;,OZ8?+,,~:~~~~:,:~:,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.~OZOO8OOZZ$$I++?I7777I7I7N7?I7?=?=~:::,.......I$:,,.,,:~~=~:,,::,:&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,7OOOOOOOZOZ7I+?I$$7$$777$I7D8III=:,:,...:.:~:,.....,,:~:~:,,,:,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,:OOOOOOOOOO$$?=?$Z$77$$$$7?++?$Z7?+7+~~~=~~,,.....,,,:~~~:,,,,:,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,<br>
,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,OOOOOOOOOZ$$II$Z$$77ZZ$ZZ7?==~~~~=~~~::,........,,,::::,,,,:~,,..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,<br>
,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,:$OOOOO888Z$$I$$$$$$$$Z$ZZ$I?+=~~=:=~~,,::,,...,,,::::,,::~~,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,<br>
,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,:$OOOOOOOOZ$77$$Z$Z$$$$$$$77??+++==+~~:,,...,,,,,,::,,::=~,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,<br>
,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,7OOOOOOZOZIIIO$$$$Z$$$777II77??+++=~:,,,,,,,,:,,,,,::=~,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,<br>
,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,+OOOOOZOO$I77O$$$7$7$II?++???+++==~::,,,,,,,,,,,,::,:,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,&nbsp;.8OOOOOOZ$$77Z$7III7I??+?+=+++==~::,,,,,,,,,,,,::.,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;.OOOOOOOOZO$7II?+I?I?+=~:=~===~~::,,,,,,,,,,,,,.,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..,,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;.$OOOOOOZZZ$ZI=+++?++==~::~~::::,,,,:,,,,,,,,..,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;.&nbsp;:8OOOOOOZZZ$+??+++===~:~~:::,,,,,,,,,,,,,,.&nbsp;..,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ZOOO8OOOZZ$IIII?+++:~~::::::,,,,,,,.,,..&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.,</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.:8OO8O8OOZZ$7I??+=~~~=~=~=:,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,.......<span class="red">~$DNDDDD~</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:8O8888OOOZ7?+==~~=++====::::,:::..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,:,.<span class="red">=8DDDDDDDDDDDDNN</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.?88888OOZ$7?+=++???++==~~~~~,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,<span class="red">~I8NNNDN.NDDDDNDNNZ~.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,Z888OOZ$$77777777I??++~..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,<span class="red">~I8NDDNDDDDDDDD:7DDDD</span>&nbsp;..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,~+?II??+==~:,.&nbsp;..&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;..<span class="red">:$8O=DNDDDDDDDDD8?:</span>,,,,,<span class="red">DDDN:</span>,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.&nbsp;<span class="red">.7</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">,ION:</span>&nbsp;<span class="red">7DDDN,DDNDO=:DDDNI</span>,,,,,,,<span class="red">DDDDD:~$DNDNNDD:</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">DNDD8..DDDD~</span>,,,,,,,<span class="red">NDDDN</span>,,,,,,,<span class="red">$DDDDDDDDDDDDDN8</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,<span class="red">+$MDD</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">+DDDN..MDDDO</span>,,,,,,,<span class="red">$DDDD</span>,,,,,,,<span class="red">.NDDDDDNMO+</span>.....&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,<span class="red">+NDDD</span>,<span class="red">:DDDD=.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">NNDDI.=DDDN</span>,,,,,,,,<span class="red">DDDD$</span>,,,,,,,<span class="red">DDDD8</span>,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.=$DN:</span>,,,,,<span class="red">+NDDD</span>,,<span class="red">DNDD8.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">NNDDD..NNDNI</span>,,,,,,,<span class="red">ODDDD</span>,,,,,,,<span class="red">+DDDN:</span>,,,,,,,.....&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.&nbsp;..</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">ODDDDN</span>,,,,,<span class="red">+NDND</span>,,<span class="red">+NDNN</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">~NDDN=&nbsp;8DDDD</span>,,,,,,,<span class="red">:DDDD:</span>,,,,,,,<span class="red">NDDDD</span>,,,,<span class="red">:IDNNDDD.</span>&nbsp;<br>
&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">$DDDNZ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">ODDDDDO</span>,,,,<span class="red">+NDDZ</span>,,,<span class="red">DDDD7IONNDDDDDDDN8.,DDDN~</span>,,,,,,,<span class="red">NDDDZ</span>,,,,,,,<span class="red">ONDDDNNDDDDDDDDDD.</span>&nbsp;<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">+NDNDI</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">ONDNNDNI</span>,,,<span class="red">+NDN7</span>,,,<span class="red">NDDDDDDDDDDNNNNDNN</span>&nbsp;<span class="red">.NDDD8</span>,,,,,,,<span class="red">IDDDN</span>,,,,,,,<span class="red">:NDDDDDDDNNNZ+</span>.,.&nbsp;&nbsp;<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">ODDDD,.</span>&nbsp;<span class="red">.ZDDN,DDD~</span>,,<span class="red">+NDD+</span>,,,<span class="red">~NDDDND+</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">NDDDI&nbsp;=DDNN</span>,,,,,,,,<span class="red">NDDN+:</span>,,,,,,<span class="red">8NNN?</span>,:,,,,,,,,,,&nbsp;<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.DDDDN.</span>&nbsp;<span class="red">,$DDN,ODDN</span>,,<span class="red">+NDN=</span>,,,,<span class="red">NDDD$.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">DDDDD&nbsp;.NDDD7</span>,,,,,,,<span class="red">NDDND</span>,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">DDDND.,7NDN</span>,,<span class="red">DDDD,+NDN~</span>,,,,<span class="red">ZDDDN.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">:DDDN,.DDDDN</span>,,,,,,,<span class="red">~7</span>,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.NDDDO,?DDN</span>,,<span class="red">~DDD?+NDN:</span>,,,,<span class="red">~DDDNI</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">NDDD7.~NDDD</span>,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">DDDD?+NDN.</span>,,<span class="red">+NDDINDN</span>,,,,,,<span class="red">NNDNN</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">ZNNN8.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.NDDN=DDN.</span>,,,<span class="red">$NDDDDD</span>,,,,,,<span class="red">IDDDD.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.DDDNDDD.</span>,,,,<span class="red">NDDDDD</span>,,,,,,,<span class="red">NN8I.</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="red">.,NDDDDD.</span>,,,,,<span class="red">NDDDD</span>,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,<span class="red">~NDDDD.</span>,,,,,<span class="red">::</span>,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,<span class="red">+N87.</span>,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,<span class="blue">#####</span>,<span class="blue">##</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">#####</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,<span class="blue">#</span>,,,,,,,,,<span class="blue">##</span>,,,,,<span class="blue">#</span>,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">####</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,<span class="blue">#</span>,,,&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,<span class="blue">#</span>,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">##</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,<span class="blue">#</span>,,.&nbsp;<span class="blue">####</span>&nbsp;&nbsp;&nbsp;<span class="blue">##</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;<span class="blue">####</span>,<span class="blue">##</span>,,<span class="blue">#####</span>,,,<span class="blue">#</span>,<span class="blue">##</span>,<span class="blue">##</span>,,<span class="blue">#####</span>,,,<span class="blue">####</span>&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">###</span>&nbsp;&nbsp;<span class="blue">########</span>,,,<span class="blue">##</span>,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,<span class="blue">#</span>,,&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">####</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>,<span class="blue">#</span>,,<span class="blue">#</span>,,,<span class="blue">#</span>,,<span class="blue">#</span>,,,<span class="blue">###</span>,,,<span class="blue">#</span>,,,<span class="blue">#</span>,,<span class="blue">#</span>,,<span class="blue">#</span>,,<span class="blue">#</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">###</span>&nbsp;<span class="blue">###</span>&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>.,<span class="blue">####</span>,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,<span class="blue">#</span>,.&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>,,,,<span class="blue">#</span>,,,<span class="blue">#</span>,,<span class="blue">#</span>,,,<span class="blue">###</span>,,,<span class="blue">#</span>,,,<span class="blue">#</span>,,<span class="blue">#</span>,,<span class="blue">####</span>.&nbsp;&nbsp;&nbsp;<span class="blue">##</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;<span class="blue">#</span>&nbsp;&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>&nbsp;&nbsp;<span class="blue">#</span>.,<span class="blue">#</span>,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,<span class="blue">###</span>&nbsp;&nbsp;<span class="blue">######</span>&nbsp;&nbsp;<span class="blue">###</span>&nbsp;&nbsp;&nbsp;<span class="blue">#####&nbsp;&nbsp;<span class="blue">###</span>,,<span class="blue">###</span>,<span class="blue">######</span>,<span class="blue">#####</span>,<span class="blue">###</span>,<span class="blue">######</span>,<span class="blue">#####</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="blue">####</span>&nbsp;&nbsp;<span class="blue">##</span>&nbsp;<span class="blue">#</span>&nbsp;<span class="blue">#########</span>.,<span class="blue">###</span>,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<span class="blue">#</span>,,,<span class="blue">#</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<br>
,,,,,,,,,,,,,,,,,,,,,,,,,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<span class="blue">####</span>,.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,</h1>
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<img src="img/divider-cat.gif" width="480px" height="65px" alt="">
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<h2>The game begins when Jon says:</h2>
				<p class="quote">"I dunno, guys -- maybe this is actually a real-time opportunity to leverage the dynamism of our brand narrative through synergized customer-engagement appropriations of emerging new-media relationships!"</p>
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<img src="img/divider-cats.gif" width="600px" height="80px" alt="">
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<h2>The Rules</h2>
				<ol>
					<li><span class="description">If Jon says a word with 5 or more syllables, everybody drinks.</span></li>
					<li><span class="description">If Jon says 3 words with 3 syllables or more in a row, everybody finishes their drink.</span></li>
					<li><span class="description">If someone says "<a href="#cat-gif">cat gif</a>" and Jon smiles, then he has to drink. If Jon does not smile, the initiator drinks.</span></li>
					<li><span class="description">If Jon says [<a href="#x">any of these words</a>] everybody drinks.</span></li>
				</ol>
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<h2><a name="cat-gif"></a>Example Cat GIFs</h2>
				<img src="img/cat03.gif"> <img src="img/cat04.gif"> <img src="img/cat05.gif"> <img src="img/cat06.gif"> <img src="img/cat07.gif"> <img src="img/cat01.gif"> <img src="img/cat02.gif">
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<h2><a name="x"></a>Official List of Words</h2>
				<p class="aside">gorgeous, beautiful, canonical, prohibitively, radically, actualized, mindfully, calcification, incredibly, betterment, paradoxically, assumption, harmonious, presentational, joyful, consistent, measurable, leanness, clean, exemplary, conflated, conventional, quasi, circuitous, intermediary, nerdy, strictly, explicitly, implication, skeptically, judicious, insistently, web, futility, interactive, flexible, unusable, cynical, schadenfreude, plausible, context, obligatory, semantics, policy, bifurcation, disparate, conversely, abysmal, abstracted, opaque, snarky, curmudgeon, representation, conversely, trajectory, meaningful, forehead-slappingly, myriad, proprietary, deliberately, conceivably, [redacted], logically, Goog-fu.</p>
				<p class="aside">ANY WORD ENDING IN -LY</p>
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<h2><a name="cat-gif"></a>More Cat GIFs for Your Viewing Pleasure</h2>
				<img src="img/cat08.gif"> <img src="img/cat09.gif"> <img src="img/cat11.gif"> <img src="img/cat10.gif"> <img src="img/cat12.gif"> <img src="img/cat13.gif"> <img src="img/cat14.gif"> <img src="img/cat15.gif"> <img src="img/cat16.gif"> <img src="img/cat17.gif">
			</td>
		</tr>
		<tr>
			<td align="center" valign="middle"><img src="img/ie.gif" width="88px" height="31px" alt=""></td>
			<td align="center" valign="middle"><img src="img/under-construction.gif" width="128px" height="40px" alt=""></td>
			<td align="center" valign="middle"><img src="img/netscape.gif" width="88px" height="31px" alt=""></td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<img src="img/good-day.gif" width="464px" height="234px" alt="">
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<embed src="media/rick-astley.mid" autostart="true" loop="1" controls="smallconsole">
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center" valign="middle">
				<!-- hitwebcounter Code START -->
				<a href="http://www.hitwebcounter.com/" target="_blank">
				<img src="http://hitwebcounter.com/counter/counter.php?page=4622912&style=0036&nbdigits=9&type=page&initCount=298467" title="" Alt=""   border="0" >
				</a>
			</td>
		</tr>
	</tbody>
</table>
</body>
</html>